name: Auto build the project when push event call
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repository
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
      - name: Notify Slack on failure
        run: echo "Hello World"
